package com.myspace.solar_village_poc_v2.datamodal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Customer() {
    }




}